# Generated by Django 5.1.5 on 2025-01-24 05:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AddField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount (₹)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(max_length=50, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='college',
            field=models.CharField(max_length=100, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='events',
            field=models.TextField(verbose_name='Selected Events'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_screenshot',
            field=models.ImageField(upload_to=app.models.custom_filename, verbose_name='Payment Screenshot'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(max_length=10, verbose_name='Year of Study'),
        ),
    ]
